### ISSUE TITLE
Profile To-Do's

### ISSUE THREAD

**Issue by D-Baugh** [D-Baugh/DB-Portfolio#1]
- [x]  Finish Page styling with CSS
- [x]  style  JavaScript Games & Funnies section via css
- [ ]  append script section elements into script section 
- [ ] Add a simple game made with Javascript for skill showcasing  (utilize classes & methods for this, need to showcase capability)
- [ ] More features and information to come
